const initialFoodItems = [
  // South Indian
  {
    name: 'Idli',
    category: 'South Indian',
    defaultUnit: 'piece',
    calories: 65,
    protein: 2.2,
    carbs: 14.0,
    fat: 0.2,
    fiber: 0.8,
    isIndian: true,
    servingSizes: [
      { unit: 'piece', grams: 50, calories: 65, protein: 2.2, carbs: 14.0, fat: 0.2, fiber: 0.8 },
      { unit: 'plate (2 pcs)', grams: 100, calories: 130, protein: 4.4, carbs: 28.0, fat: 0.4, fiber: 1.6 },
    ],
  },
  {
    name: 'Plain Dosa',
    category: 'South Indian',
    defaultUnit: 'piece',
    calories: 130,
    protein: 3.5,
    carbs: 23.0,
    fat: 3.0,
    fiber: 1.2,
    isIndian: true,
    servingSizes: [
      { unit: 'piece', grams: 80, calories: 130, protein: 3.5, carbs: 23.0, fat: 3.0, fiber: 1.2 },
      { unit: 'large dosa', grams: 120, calories: 195, protein: 5.2, carbs: 34.5, fat: 4.5, fiber: 1.8 },
    ],
  },
  {
    name: 'Masala Dosa',
    category: 'South Indian',
    defaultUnit: 'piece',
    calories: 250,
    protein: 5.5,
    carbs: 38.0,
    fat: 9.0,
    fiber: 3.0,
    isIndian: true,
    servingSizes: [
      { unit: 'piece', grams: 150, calories: 250, protein: 5.5, carbs: 38.0, fat: 9.0, fiber: 3.0 },
    ],
  },
  {
    name: 'Medu Vada',
    category: 'South Indian',
    defaultUnit: 'piece',
    calories: 150,
    protein: 4.0,
    carbs: 16.0,
    fat: 8.0,
    fiber: 2.1,
    isIndian: true,
    servingSizes: [
      { unit: 'piece', grams: 50, calories: 150, protein: 4.0, carbs: 16.0, fat: 8.0, fiber: 2.1 },
    ],
  },
  {
    name: 'Mysore Bonda',
    category: 'South Indian',
    defaultUnit: 'piece',
    calories: 140,
    protein: 3.0,
    carbs: 18.0,
    fat: 6.5,
    fiber: 1.0,
    isIndian: true,
    servingSizes: [
      { unit: 'piece', grams: 45, calories: 140, protein: 3.0, carbs: 18.0, fat: 6.5, fiber: 1.0 },
    ],
  },
  {
    name: 'Upma',
    category: 'South Indian',
    defaultUnit: 'bowl',
    calories: 210,
    protein: 4.5,
    carbs: 35.0,
    fat: 6.0,
    fiber: 2.5,
    isIndian: true,
    servingSizes: [
      { unit: 'bowl', grams: 150, calories: 210, protein: 4.5, carbs: 35.0, fat: 6.0, fiber: 2.5 },
      { unit: 'cup', grams: 100, calories: 140, protein: 3.0, carbs: 23.3, fat: 4.0, fiber: 1.7 },
    ],
  },
  {
    name: 'Ven Pongal',
    category: 'South Indian',
    defaultUnit: 'bowl',
    calories: 260,
    protein: 6.0,
    carbs: 40.0,
    fat: 8.5,
    fiber: 3.0,
    isIndian: true,
    servingSizes: [
      { unit: 'bowl', grams: 180, calories: 260, protein: 6.0, carbs: 40.0, fat: 8.5, fiber: 3.0 },
    ],
  },
  {
    name: 'Puri',
    category: 'South Indian',
    defaultUnit: 'piece',
    calories: 120,
    protein: 2.0,
    carbs: 15.0,
    fat: 6.0,
    fiber: 1.0,
    isIndian: true,
    servingSizes: [
      { unit: 'piece', grams: 35, calories: 120, protein: 2.0, carbs: 15.0, fat: 6.0, fiber: 1.0 },
    ],
  },
  {
    name: 'Sambar',
    category: 'South Indian',
    defaultUnit: 'bowl',
    calories: 110,
    protein: 5.0,
    carbs: 18.0,
    fat: 2.5,
    fiber: 4.0,
    isIndian: true,
    servingSizes: [
      { unit: 'bowl', grams: 150, calories: 110, protein: 5.0, carbs: 18.0, fat: 2.5, fiber: 4.0 },
      { unit: 'cup', grams: 100, calories: 73, protein: 3.3, carbs: 12.0, fat: 1.7, fiber: 2.7 },
    ],
  },
  {
    name: 'Coconut Chutney',
    category: 'South Indian',
    defaultUnit: 'tablespoon',
    calories: 45,
    protein: 0.8,
    carbs: 2.0,
    fat: 4.0,
    fiber: 1.1,
    isIndian: true,
    servingSizes: [
      { unit: 'tablespoon', grams: 20, calories: 45, protein: 0.8, carbs: 2.0, fat: 4.0, fiber: 1.1 },
      { unit: 'small bowl', grams: 50, calories: 112, protein: 2.0, carbs: 5.0, fat: 10.0, fiber: 2.75 },
    ],
  },
  {
    name: 'Groundnut Chutney (Peanut)',
    category: 'South Indian',
    defaultUnit: 'tablespoon',
    calories: 60,
    protein: 2.5,
    carbs: 3.0,
    fat: 4.5,
    fiber: 1.0,
    isIndian: true,
    servingSizes: [
      { unit: 'tablespoon', grams: 20, calories: 60, protein: 2.5, carbs: 3.0, fat: 4.5, fiber: 1.0 },
      { unit: 'small bowl', grams: 50, calories: 150, protein: 6.25, carbs: 7.5, fat: 11.25, fiber: 2.5 },
    ],
  },
  {
    name: 'Lemon Rice',
    category: 'South Indian',
    defaultUnit: 'bowl',
    calories: 270,
    protein: 4.5,
    carbs: 45.0,
    fat: 8.0,
    fiber: 2.0,
    isIndian: true,
    servingSizes: [
      { unit: 'bowl', grams: 180, calories: 270, protein: 4.5, carbs: 45.0, fat: 8.0, fiber: 2.0 },
    ],
  },
  {
    name: 'Curd Rice',
    category: 'South Indian',
    defaultUnit: 'bowl',
    calories: 220,
    protein: 5.5,
    carbs: 34.0,
    fat: 7.0,
    fiber: 1.2,
    isIndian: true,
    servingSizes: [
      { unit: 'bowl', grams: 200, calories: 220, protein: 5.5, carbs: 34.0, fat: 7.0, fiber: 1.2 },
    ],
  },

  // Rice & Meals
  {
    name: 'Cooked White Rice',
    category: 'Rice & Meals',
    defaultUnit: 'bowl',
    calories: 205,
    protein: 4.2,
    carbs: 45.0,
    fat: 0.4,
    fiber: 0.6,
    isIndian: true,
    servingSizes: [
      { unit: 'bowl', grams: 150, calories: 205, protein: 4.2, carbs: 45.0, fat: 0.4, fiber: 0.6 },
      { unit: '100g', grams: 100, calories: 136, protein: 2.8, carbs: 30.0, fat: 0.3, fiber: 0.4 },
      { unit: 'cup', grams: 160, calories: 218, protein: 4.5, carbs: 48.0, fat: 0.5, fiber: 0.6 },
    ],
  },
  {
    name: 'Cooked Brown Rice',
    category: 'Rice & Meals',
    defaultUnit: 'bowl',
    calories: 215,
    protein: 5.0,
    carbs: 45.0,
    fat: 1.8,
    fiber: 3.5,
    isIndian: false,
    servingSizes: [
      { unit: 'bowl', grams: 150, calories: 215, protein: 5.0, carbs: 45.0, fat: 1.8, fiber: 3.5 },
      { unit: '100g', grams: 100, calories: 143, protein: 3.3, carbs: 30.0, fat: 1.2, fiber: 2.3 },
    ],
  },
  {
    name: 'Yellow Dal Tadka',
    category: 'Rice & Meals',
    defaultUnit: 'bowl',
    calories: 180,
    protein: 9.0,
    carbs: 26.0,
    fat: 4.5,
    fiber: 6.0,
    isIndian: true,
    servingSizes: [
      { unit: 'bowl', grams: 150, calories: 180, protein: 9.0, carbs: 26.0, fat: 4.5, fiber: 6.0 },
    ],
  },
  {
    name: 'Chicken Biryani',
    category: 'Rice & Meals',
    defaultUnit: 'plate',
    calories: 480,
    protein: 28.0,
    carbs: 55.0,
    fat: 16.0,
    fiber: 3.2,
    isIndian: true,
    servingSizes: [
      { unit: 'plate', grams: 350, calories: 480, protein: 28.0, carbs: 55.0, fat: 16.0, fiber: 3.2 },
      { unit: 'half plate', grams: 200, calories: 275, protein: 16.0, carbs: 31.0, fat: 9.0, fiber: 1.8 },
    ],
  },
  {
    name: 'Veg Biryani',
    category: 'Rice & Meals',
    defaultUnit: 'plate',
    calories: 360,
    protein: 8.5,
    carbs: 58.0,
    fat: 11.0,
    fiber: 5.0,
    isIndian: true,
    servingSizes: [
      { unit: 'plate', grams: 300, calories: 360, protein: 8.5, carbs: 58.0, fat: 11.0, fiber: 5.0 },
    ],
  },
  {
    name: 'Chapati / Roti',
    category: 'Rice & Meals',
    defaultUnit: 'piece',
    calories: 85,
    protein: 3.0,
    carbs: 16.0,
    fat: 0.8,
    fiber: 2.5,
    isIndian: true,
    servingSizes: [
      { unit: 'piece', grams: 35, calories: 85, protein: 3.0, carbs: 16.0, fat: 0.8, fiber: 2.5 },
      { unit: 'butter roti', grams: 40, calories: 115, protein: 3.0, carbs: 16.0, fat: 4.5, fiber: 2.5 },
    ],
  },

  // Protein
  {
    name: 'Boiled Egg',
    category: 'Protein',
    defaultUnit: 'piece',
    calories: 78,
    protein: 6.3,
    carbs: 0.6,
    fat: 5.3,
    fiber: 0,
    isIndian: false,
    servingSizes: [
      { unit: 'piece', grams: 50, calories: 78, protein: 6.3, carbs: 0.6, fat: 5.3, fiber: 0 },
      { unit: 'egg white', grams: 33, calories: 17, protein: 3.6, carbs: 0.2, fat: 0.1, fiber: 0 },
    ],
  },
  {
    name: 'Egg Omelette (2 Eggs)',
    category: 'Protein',
    defaultUnit: 'serving',
    calories: 210,
    protein: 13.0,
    carbs: 1.5,
    fat: 17.0,
    fiber: 0.2,
    isIndian: true,
    servingSizes: [
      { unit: 'serving', grams: 120, calories: 210, protein: 13.0, carbs: 1.5, fat: 17.0, fiber: 0.2 },
    ],
  },
  {
    name: 'Grilled Chicken Breast',
    category: 'Protein',
    defaultUnit: '100g',
    calories: 165,
    protein: 31.0,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    isIndian: false,
    servingSizes: [
      { unit: '100g', grams: 100, calories: 165, protein: 31.0, carbs: 0, fat: 3.6, fiber: 0 },
      { unit: '150g piece', grams: 150, calories: 247, protein: 46.5, carbs: 0, fat: 5.4, fiber: 0 },
    ],
  },
  {
    name: 'Chicken Curry',
    category: 'Protein',
    defaultUnit: 'bowl',
    calories: 280,
    protein: 24.0,
    carbs: 8.0,
    fat: 17.0,
    fiber: 1.5,
    isIndian: true,
    servingSizes: [
      { unit: 'bowl', grams: 200, calories: 280, protein: 24.0, carbs: 8.0, fat: 17.0, fiber: 1.5 },
    ],
  },
  {
    name: 'Paneer (Raw / Fresh)',
    category: 'Protein',
    defaultUnit: '100g',
    calories: 265,
    protein: 18.0,
    carbs: 3.5,
    fat: 20.0,
    fiber: 0,
    isIndian: true,
    servingSizes: [
      { unit: '100g', grams: 100, calories: 265, protein: 18.0, carbs: 3.5, fat: 20.0, fiber: 0 },
      { unit: '50g portion', grams: 50, calories: 132, protein: 9.0, carbs: 1.75, fat: 10.0, fiber: 0 },
    ],
  },
  {
    name: 'Paneer Butter Masala',
    category: 'Protein',
    defaultUnit: 'bowl',
    calories: 340,
    protein: 14.0,
    carbs: 12.0,
    fat: 26.0,
    fiber: 2.0,
    isIndian: true,
    servingSizes: [
      { unit: 'bowl', grams: 200, calories: 340, protein: 14.0, carbs: 12.0, fat: 26.0, fiber: 2.0 },
    ],
  },
  {
    name: 'Whole Milk (Full Cream)',
    category: 'Protein',
    defaultUnit: 'cup',
    calories: 150,
    protein: 8.0,
    carbs: 12.0,
    fat: 8.0,
    fiber: 0,
    isIndian: false,
    servingSizes: [
      { unit: 'cup', grams: 240, calories: 150, protein: 8.0, carbs: 12.0, fat: 8.0, fiber: 0 },
      { unit: 'glass (300ml)', grams: 300, calories: 188, protein: 10.0, carbs: 15.0, fat: 10.0, fiber: 0 },
    ],
  },
  {
    name: 'Plain Curd / Dahi',
    category: 'Protein',
    defaultUnit: 'bowl',
    calories: 100,
    protein: 5.5,
    carbs: 7.0,
    fat: 6.0,
    fiber: 0,
    isIndian: true,
    servingSizes: [
      { unit: 'bowl', grams: 150, calories: 100, protein: 5.5, carbs: 7.0, fat: 6.0, fiber: 0 },
      { unit: 'cup', grams: 100, calories: 67, protein: 3.7, carbs: 4.7, fat: 4.0, fiber: 0 },
    ],
  },

  // Snacks & Fruits
  {
    name: 'Banana',
    category: 'Snacks',
    defaultUnit: 'piece',
    calories: 105,
    protein: 1.3,
    carbs: 27.0,
    fat: 0.3,
    fiber: 3.1,
    isIndian: false,
    servingSizes: [
      { unit: 'medium piece', grams: 118, calories: 105, protein: 1.3, carbs: 27.0, fat: 0.3, fiber: 3.1 },
      { unit: 'large piece', grams: 140, calories: 125, protein: 1.5, carbs: 32.0, fat: 0.4, fiber: 3.5 },
    ],
  },
  {
    name: 'Apple',
    category: 'Snacks',
    defaultUnit: 'piece',
    calories: 95,
    protein: 0.5,
    carbs: 25.0,
    fat: 0.3,
    fiber: 4.4,
    isIndian: false,
    servingSizes: [
      { unit: 'medium piece', grams: 180, calories: 95, protein: 0.5, carbs: 25.0, fat: 0.3, fiber: 4.4 },
    ],
  },
  {
    name: 'Roasted Peanuts',
    category: 'Snacks',
    defaultUnit: 'handful',
    calories: 165,
    protein: 7.3,
    carbs: 6.0,
    fat: 14.0,
    fiber: 2.4,
    isIndian: true,
    servingSizes: [
      { unit: 'handful (30g)', grams: 30, calories: 165, protein: 7.3, carbs: 6.0, fat: 14.0, fiber: 2.4 },
      { unit: '100g', grams: 100, calories: 567, protein: 25.8, carbs: 16.0, fat: 49.0, fiber: 8.5 },
    ],
  },
  {
    name: 'Almonds',
    category: 'Snacks',
    defaultUnit: 'handful',
    calories: 160,
    protein: 6.0,
    carbs: 6.0,
    fat: 14.0,
    fiber: 3.5,
    isIndian: false,
    servingSizes: [
      { unit: '10-12 pieces (28g)', grams: 28, calories: 160, protein: 6.0, carbs: 6.0, fat: 14.0, fiber: 3.5 },
    ],
  },
  {
    name: 'Digestive Biscuits',
    category: 'Snacks',
    defaultUnit: 'piece',
    calories: 70,
    protein: 1.1,
    carbs: 10.5,
    fat: 2.8,
    fiber: 0.8,
    isIndian: false,
    servingSizes: [
      { unit: '2 biscuits', grams: 30, calories: 140, protein: 2.2, carbs: 21.0, fat: 5.6, fiber: 1.6 },
    ],
  },
];

module.exports = initialFoodItems;
